name: Run Trading Bot Daily at 9:15 AM IST

on:
  schedule:
    - cron: '45 15 * * 1-5'   # Runs at 9:15 AM IST (3:45 AM UTC)
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOTP_TOKEN: ${{ secrets.TOTP_TOKEN }}
        run: python main.py
